// Gerado automaticamente — capacidades extraídas do livropkm.pdf
export const POKEMON_CAPACIDADE_MAP = {
  'Abomasnow': { forca: 4, inteligencia: 4, salto: 3 },
  'Abra': { forca: 1, inteligencia: 4, salto: '' },
  'Absol': { forca: 3, inteligencia: 4, salto: 4 },
  'Accelgor': { forca: 3, inteligencia: 4, salto: 4 },
  'Aegislash': { forca: 4, inteligencia: 4, salto: 1 },
  'Aerodactyl': { forca: 5, inteligencia: 4, salto: 4 },
  'Aggron': { forca: 5, inteligencia: 4, salto: 3 },
  'Aipom': { forca: 2, inteligencia: 4, salto: 5 },
  'Alakazam': { forca: 2, inteligencia: 7, salto: 2 },
  'Alomomola': { forca: 3, inteligencia: 4, salto: 2 },
  'Altaria': { forca: 2, inteligencia: 4, salto: 2 },
  'Amaura': { forca: 3, inteligencia: 4, salto: 2 },
  'Ambipom': { forca: 3, inteligencia: 4, salto: 5 },
  'Amoonguss': { forca: 3, inteligencia: 4, salto: 1 },
  'Ampharos': { forca: 3, inteligencia: 4, salto: 3 },
  'Anorith': { forca: 1, inteligencia: 2, salto: 1 },
  'Araquanid': { forca: 4, inteligencia: 4, salto: 5 },
  'Arbok': { forca: 3, inteligencia: 4, salto: 2 },
  'Arcanine': { forca: 4, inteligencia: 4, salto: 5 },
  'Arceus': { forca: 10, inteligencia: 7, salto: 10 },
  'Arceus (Placa Chama)': { forca: 10, inteligencia: 7, salto: 10 },
  'Arceus (Placa Dragão)': { forca: 10, inteligencia: 7, salto: 10 },
  'Arceus (Placa Eletro)': { forca: 10, inteligencia: 7, salto: 10 },
  'Arceus (Placa Fada)': { forca: 10, inteligencia: 7, salto: 10 },
  'Arceus (Placa Fantasma)': { forca: 10, inteligencia: 7, salto: 10 },
  'Arceus (Placa Gelo)': { forca: 10, inteligencia: 7, salto: 10 },
  'Arceus (Placa Grama)': { forca: 10, inteligencia: 7, salto: 10 },
  'Arceus (Placa Inseto)': { forca: 10, inteligencia: 7, salto: 10 },
  'Arceus (Placa Luta)': { forca: 10, inteligencia: 7, salto: 10 },
  'Arceus (Placa Metálico)': { forca: 10, inteligencia: 7, salto: 10 },
  'Arceus (Placa Pedra)': { forca: 10, inteligencia: 7, salto: 10 },
  'Arceus (Placa Psíquico)': { forca: 10, inteligencia: 7, salto: 10 },
  'Arceus (Placa Sombrio)': { forca: 10, inteligencia: 7, salto: 10 },
  'Arceus (Placa Terra)': { forca: 10, inteligencia: 7, salto: 10 },
  'Arceus (Placa Veneno)': { forca: 10, inteligencia: 7, salto: 10 },
  'Arceus (Placa Voador)': { forca: 10, inteligencia: 7, salto: 10 },
  'Arceus (Placa Água)': { forca: 10, inteligencia: 7, salto: 10 },
  'Archen': { forca: 1, inteligencia: 4, salto: 5 },
  'Archeops': { forca: 2, inteligencia: 4, salto: 6 },
  'Ariados': { forca: 2, inteligencia: 4, salto: 6 },
  'Armaldo': { forca: 4, inteligencia: 4, salto: 3 },
  'Aromatisse': { forca: 3, inteligencia: 4, salto: 2 },
  'Aron': { forca: 2, inteligencia: 3, salto: 3 },
  'Articuno': { forca: 5, inteligencia: 7, salto: 5 },
  'Audino': { forca: 3, inteligencia: 4, salto: 2 },
  'Aurorus': { forca: 5, inteligencia: 4, salto: 2 },
  'Avalugg': { forca: 8, inteligencia: 4, salto: 1 },
  'Axew': { forca: 3, inteligencia: 2, salto: 4 },
  'Azelf': { forca: 2, inteligencia: 7, salto: 5 },
  'Azumarill': { forca: 4, inteligencia: 4, salto: 4 },
  'Azurill': { forca: 1, inteligencia: 2, salto: 1 },
  'Bagon': { forca: 2, inteligencia: 3, salto: 3 },
  'Baltoy': { forca: 2, inteligencia: 4, salto: 3 },
  'Banette': { forca: 3, inteligencia: 4, salto: 3 },
  'Barbaracle': { forca: 3, inteligencia: 4, salto: 2 },
  'Barboach': { forca: 1, inteligencia: 3, salto: 3 },
  'Basculin': { forca: 4, inteligencia: 3, salto: 4 },
  'Bastiodon': { forca: 4, inteligencia: 4, salto: 3 },
  'Bayleef': { forca: 4, inteligencia: 4, salto: 3 },
  'Beartic': { forca: 4, inteligencia: 4, salto: 3 },
  'Beautifly': { forca: 3, inteligencia: 4, salto: 3 },
  'Beedrill': { forca: 3, inteligencia: 4, salto: 3 },
  'Beheeyem': { forca: 3, inteligencia: 6, salto: 3 },
  'Beldum': { forca: 3, inteligencia: 5, salto: 1 },
  'Bellossom': { forca: 2, inteligencia: 4, salto: 3 },
  'Bellsprout': { forca: 1, inteligencia: 2, salto: 1 },
  'Bergmite': { forca: 3, inteligencia: 3, salto: 1 },
  'Bewear': { forca: 7, inteligencia: 3, salto: 3 },
  'Bibarel': { forca: 3, inteligencia: 3, salto: 3 },
  'Bidoof': { forca: 1, inteligencia: 2, salto: 2 },
  'Binacle': { forca: 1, inteligencia: 3, salto: 1 },
  'Bisharp': { forca: 4, inteligencia: 4, salto: 4 },
  'Blacephalon': { forca: 3, inteligencia: 4, salto: 4 },
  'Blastoise': { forca: 4, inteligencia: 4, salto: 1 },
  'Blaziken': { forca: 5, inteligencia: 4, salto: 7 },
  'Blissey': { forca: 3, inteligencia: 4, salto: 3 },
  'Blitzle': { forca: 2, inteligencia: 4, salto: 4 },
  'Boldore': { forca: 4, inteligencia: 4, salto: 1 },
  'Bonsly': { forca: 1, inteligencia: 3, salto: 2 },
  'Bouffalant': { forca: 4, inteligencia: 3, salto: 3 },
  'Bounsweet': { forca: 1, inteligencia: 3, salto: 2 },
  'Braixen': { forca: 3, inteligencia: 5, salto: 3 },
  'Braviary': { forca: 4, inteligencia: 3, salto: 3 },
  'Breloom': { forca: 3, inteligencia: 4, salto: 3 },
  'Brionne': { forca: 3, inteligencia: 4, salto: 2 },
  'Bronzong': { forca: 4, inteligencia: 4, salto: 2 },
  'Bronzor': { forca: 3, inteligencia: 4, salto: 2 },
  'Bruxish': { forca: 2, inteligencia: 4, salto: 2 },
  'Budew': { forca: 1, inteligencia: 3, salto: 2 },
  'Buizel': { forca: 2, inteligencia: 4, salto: 2 },
  'Bulbassauro': { forca: 1, inteligencia: 3, salto: 2 },
  'Buneary': { forca: 1, inteligencia: 2, salto: 5 },
  'Bunnelby': { forca: 2, inteligencia: 3, salto: 3 },
  'Burmy': { forca: 1, inteligencia: 2, salto: 3 },
  'Butterfree': { forca: 3, inteligencia: 4, salto: 3 },
  'Buzzwole': { forca: 10, inteligencia: 4, salto: 3 },
  'Cacnea': { forca: 2, inteligencia: 4, salto: 3 },
  'Cacturne': { forca: 3, inteligencia: 4, salto: 3 },
  'Carbink': { forca: 2, inteligencia: 4, salto: 2 },
  'Carnivine': { forca: 2, inteligencia: 4, salto: 3 },
  'Carracosta': { forca: 4, inteligencia: 4, salto: 2 },
  'Carvanha': { forca: 1, inteligencia: 4, salto: 3 },
  'Cascoon': { forca: 2, inteligencia: 2, salto: 4 },
  'Castform': { forca: 1, inteligencia: 4, salto: 2 },
  'Caterpie': { forca: 2, inteligencia: 2, salto: 2 },
  'Celebi': { forca: 3, inteligencia: 7, salto: 6 },
  'Celesteela': { forca: 10, inteligencia: 4, salto: 8 },
  'Chandelure': { forca: 1, inteligencia: 4, salto: 2 },
  'Chansey': { forca: 2, inteligencia: 4, salto: 2 },
  'Charizard': { forca: 4, inteligencia: 4, salto: 2 },
  'Charjabug': { forca: 1, inteligencia: 3, salto: 1 },
  'Charmander': { forca: 1, inteligencia: 3, salto: 3 },
  'Charmeleon': { forca: 2, inteligencia: 3, salto: 3 },
  'Chatot': { forca: 1, inteligencia: 4, salto: 3 },
  'Cherrim': { forca: 1, inteligencia: 4, salto: 4 },
  'Cherubi': { forca: 1, inteligencia: 3, salto: 4 },
  'Chesnaught': { forca: 4, inteligencia: 4, salto: 3 },
  'Chespin': { forca: 2, inteligencia: 3, salto: 2 },
  'Chikorita': { forca: 1, inteligencia: 3, salto: 2 },
  'Chimchar': { forca: 1, inteligencia: 3, salto: 2 },
  'Chimecho': { forca: 1, inteligencia: 4, salto: 2 },
  'Chinchou': { forca: 1, inteligencia: 3, salto: 2 },
  'Chingling': { forca: 1, inteligencia: 4, salto: 2 },
  'Cinccino': { forca: 2, inteligencia: 4, salto: 3 },
  'Clamperl': { forca: 2, inteligencia: 3, salto: 2 },
  'Clauncher': { forca: 2, inteligencia: 3, salto: 1 },
  'Clawitzer': { forca: 4, inteligencia: 4, salto: 1 },
  'Claydol': { forca: 3, inteligencia: 4, salto: 3 },
  'Clefable': { forca: 3, inteligencia: 4, salto: 5 },
  'Clefairy': { forca: 2, inteligencia: 3, salto: 4 },
  'Cleffa': { forca: 1, inteligencia: 3, salto: 2 },
  'Cloyster': { forca: 4, inteligencia: 4, salto: 2 },
  'Cobalion': { forca: 5, inteligencia: 5, salto: 4 },
  'Cofagrigus': { forca: 3, inteligencia: 4, salto: 3 },
  'Combee': { forca: 1, inteligencia: 2, salto: 2 },
  'Combusken': { forca: 4, inteligencia: 3, salto: 3 },
  'Comfey': { forca: 1, inteligencia: 3, salto: 2 },
  'Conkeldurr': { forca: 7, inteligencia: 4, salto: 5 },
  'Corphish': { forca: 2, inteligencia: 3, salto: 2 },
  'Corsola': { forca: 1, inteligencia: 3, salto: 2 },
  'Corsola de Galar': { forca: 1, inteligencia: 3, salto: 2 },
  'Cosmoem': { forca: 1, inteligencia: 3, salto: 1 },
  'Cosmog': { forca: 1, inteligencia: 2, salto: 1 },
  'Cottonee': { forca: 1, inteligencia: 4, salto: 5 },
  'Crabominable': { forca: 4, inteligencia: 3, salto: 3 },
  'Crabrawler': { forca: 3, inteligencia: 3, salto: 3 },
  'Cradily': { forca: 3, inteligencia: 4, salto: 4 },
  'Cranidos': { forca: 3, inteligencia: 3, salto: 4 },
  'Crawdaunt': { forca: 3, inteligencia: 4, salto: 2 },
  'Cresselia': { forca: 6, inteligencia: 7, salto: 7 },
  'Croagunk': { forca: 2, inteligencia: 4, salto: 4 },
  'Crobat': { forca: 4, inteligencia: 4, salto: 1 },
  'Croconaw': { forca: 3, inteligencia: 3, salto: 3 },
  'Crustle': { forca: 4, inteligencia: 4, salto: 1 },
  'Cryogonal': { forca: 3, inteligencia: 4, salto: 1 },
  'Cubchoo': { forca: 2, inteligencia: 3, salto: 2 },
  'Cubone': { forca: 2, inteligencia: 4, salto: 3 },
  'Cutiefly': { forca: 1, inteligencia: 3, salto: 2 },
  'Cyndaquil': { forca: 1, inteligencia: 3, salto: 3 },
  'Darkrai': { forca: 8, inteligencia: 7, salto: 7 },
  'Darmanitan': { forca: 4, inteligencia: 4, salto: 4 },
  'Darmanitan de Galar': { forca: 4, inteligencia: 4, salto: 4 },
  'Dartrix': { forca: 2, inteligencia: 3, salto: 3 },
  'Darumaka': { forca: 3, inteligencia: 4, salto: 3 },
  'Darumaka de Galar': { forca: 3, inteligencia: 4, salto: 3 },
  'Decidueye': { forca: 3, inteligencia: 4, salto: 3 },
  'Dedenne': { forca: 1, inteligencia: 4, salto: 3 },
  'Deerling': { forca: 1, inteligencia: 4, salto: 2 },
  'Deino': { forca: 2, inteligencia: 2, salto: 2 },
  'Delcatty': { forca: 2, inteligencia: 4, salto: 3 },
  'Delibird': { forca: 1, inteligencia: 4, salto: 5 },
  'Delphox': { forca: 3, inteligencia: 5, salto: 3 },
  'Deoxys': { forca: 8, inteligencia: 7, salto: 10 },
  'Dewgong': { forca: 4, inteligencia: 4, salto: 2 },
  'Dewott': { forca: 3, inteligencia: 4, salto: 3 },
  'Dewpider': { forca: 2, inteligencia: 3, salto: 3 },
  'Dhelmise': { forca: 5, inteligencia: 4, salto: 2 },
  'Dialga': { forca: 10, inteligencia: 7, salto: 8 },
  'Diancie': { forca: 4, inteligencia: 5, salto: 4 },
  'Diggersby': { forca: 3, inteligencia: 4, salto: 4 },
  'Diglett': { forca: 1, inteligencia: 3, salto: '' },
  'Diglett de Alola': { forca: 1, inteligencia: 3, salto: '' },
  'Ditto': { forca: 1, inteligencia: 4, salto: 1 },
  'Dodrio': { forca: 4, inteligencia: 5, salto: 8 },
  'Doduo': { forca: 3, inteligencia: 4, salto: 6 },
  'Donphan': { forca: 4, inteligencia: 4, salto: 3 },
  'Doublade': { forca: 3, inteligencia: 4, salto: 1 },
  'Dragalge': { forca: 3, inteligencia: 4, salto: 1 },
  'Dragonair': { forca: 2, inteligencia: 4, salto: 2 },
  'Dragonite': { forca: 5, inteligencia: 4, salto: 3 },
  'Drampa': { forca: 4, inteligencia: 3, salto: 4 },
  'Drapion': { forca: 3, inteligencia: 4, salto: 2 },
  'Dratini': { forca: 1, inteligencia: 3, salto: 2 },
  'Drifblim': { forca: 4, inteligencia: 4, salto: 4 },
  'Drifloon': { forca: 1, inteligencia: 4, salto: 4 },
  'Drilbur': { forca: 2, inteligencia: 4, salto: 2 },
  'Drowzee': { forca: 2, inteligencia: 4, salto: 2 },
  'Druddigon': { forca: 5, inteligencia: 4, salto: 3 },
  'Duckett': { forca: 1, inteligencia: 3, salto: 3 },
  'Dugtrio': { forca: 3, inteligencia: 4, salto: '' },
  'Dugtrio de Alola': { forca: 3, inteligencia: 4, salto: '' },
  'Dunsparce': { forca: 1, inteligencia: 3, salto: 1 },
  'Duosion': { forca: 1, inteligencia: 5, salto: 2 },
  'Durant': { forca: 5, inteligencia: 2, salto: 2 },
  'Dusclops': { forca: 3, inteligencia: 4, salto: 3 },
  'Dusknoir': { forca: 5, inteligencia: 4, salto: 3 },
  'Duskull': { forca: 1, inteligencia: 3, salto: 3 },
  'Dustox': { forca: 3, inteligencia: 4, salto: 3 },
  'Dwebble': { forca: 2, inteligencia: 4, salto: 1 },
  'Eelektrik': { forca: 2, inteligencia: 4, salto: 2 },
  'Eelektross': { forca: 4, inteligencia: 4, salto: 3 },
  'Eevee': { forca: 1, inteligencia: 4, salto: 3 },
  'Ekans': { forca: 1, inteligencia: 3, salto: 1 },
  'Electabuzz': { forca: 4, inteligencia: 4, salto: 3 },
  'Electivire': { forca: 5, inteligencia: 4, salto: 2 },
  'Electrike': { forca: 1, inteligencia: 3, salto: 2 },
  'Electrode': { forca: 3, inteligencia: 4, salto: 3 },
  'Elekid': { forca: 1, inteligencia: 2, salto: 1 },
  'Elgyem': { forca: 2, inteligencia: 5, salto: 3 },
  'Emboar': { forca: 6, inteligencia: 4, salto: 5 },
  'Emolga': { forca: 2, inteligencia: 4, salto: 5 },
  'Empoleon': { forca: 2, inteligencia: 3, salto: 2 },
  'Entei': { forca: 5, inteligencia: 7, salto: 7 },
  'Escavalier': { forca: 4, inteligencia: 4, salto: 1 },
  'Espeon': { forca: 2, inteligencia: 5, salto: 3 },
  'Espurr': { forca: 2, inteligencia: 4, salto: 2 },
  'Excadrill': { forca: 3, inteligencia: 4, salto: 3 },
  'Exeggcute': { forca: 1, inteligencia: 4, salto: 2 },
  'Exeggutor': { forca: 4, inteligencia: 5, salto: 3 },
  'Exeggutor de Alola': { forca: 4, inteligencia: 5, salto: 3 },
  'Exploud': { forca: 5, inteligencia: 4, salto: 3 },
  "Farfetch'd": { forca: 1, inteligencia: 4, salto: 3 },
  "Farfetch'd de Galar": { forca: 1, inteligencia: 4, salto: 3 },
  'Feebas': { forca: 1, inteligencia: 2, salto: 4 },
  'Fennekin': { forca: 3, inteligencia: 4, salto: 1 },
  'Feraligatr': { forca: 4, inteligencia: 4, salto: 2 },
  'Ferroseed': { forca: 2, inteligencia: 3, salto: 1 },
  'Ferrothorn': { forca: 3, inteligencia: 4, salto: 1 },
  'Finneon': { forca: 1, inteligencia: 4, salto: 3 },
  'Flaaffy': { forca: 2, inteligencia: 3, salto: 2 },
  'Flabébé': { forca: 1, inteligencia: 3, salto: 1 },
  'Flareon': { forca: 2, inteligencia: 4, salto: 3 },
  'Fletchinder': { forca: 2, inteligencia: 3, salto: 2 },
  'Fletchling': { forca: 2, inteligencia: 3, salto: 2 },
  'Floatzel': { forca: 2, inteligencia: 4, salto: 3 },
  'Floette': { forca: 1, inteligencia: 4, salto: 1 },
  'Florges': { forca: 1, inteligencia: 4, salto: 2 },
  'Flygon': { forca: 4, inteligencia: 4, salto: 3 },
  'Fomantis': { forca: 1, inteligencia: 3, salto: 2 },
  'Foongus': { forca: 2, inteligencia: 4, salto: 1 },
  'Forretress': { forca: 3, inteligencia: 4, salto: 4 },
  'Fraxure': { forca: 4, inteligencia: 3, salto: 3 },
  'Frillish': { forca: 1, inteligencia: 4, salto: 2 },
  'Froakie': { forca: 1, inteligencia: 3, salto: 3 },
  'Frogadier': { forca: 2, inteligencia: 4, salto: 4 },
  'Froslass': { forca: 2, inteligencia: 4, salto: 2 },
  'Furfrou': { forca: 3, inteligencia: 4, salto: 3 },
  'Furret': { forca: 3, inteligencia: 4, salto: 3 },
  'Gabite': { forca: 3, inteligencia: 4, salto: 3 },
  'Gallade': { forca: 4, inteligencia: 6, salto: 4 },
  'Galvantula': { forca: 2, inteligencia: 4, salto: 4 },
  'Garbodor': { forca: 3, inteligencia: 4, salto: 1 },
  'Garchomp': { forca: 5, inteligencia: 4, salto: 3 },
  'Gardevoir': { forca: 2, inteligencia: 7, salto: 2 },
  'Gastly': { forca: 1, inteligencia: 3, salto: '' },
  'Gastrodon': { forca: 2, inteligencia: 4, salto: 2 },
  'Genesect': { forca: 6, inteligencia: 7, salto: 5 },
  'Gengar': { forca: 3, inteligencia: 4, salto: 3 },
  'Geodude': { forca: 3, inteligencia: 2, salto: 2 },
  'Geodude de Alola': { forca: 3, inteligencia: 2, salto: 2 },
  'Gible': { forca: 1, inteligencia: 3, salto: 1 },
  'Gigalith': { forca: 4, inteligencia: 4, salto: '' },
  'Girafarig': { forca: 3, inteligencia: 4, salto: 4 },
  'Giratina': { forca: 10, inteligencia: 7, salto: 8 },
  'Glaceon': { forca: 2, inteligencia: 4, salto: 3 },
  'Glalie': { forca: 4, inteligencia: 4, salto: 3 },
  'Glameow': { forca: 1, inteligencia: 4, salto: 3 },
  'Gligar': { forca: 2, inteligencia: 4, salto: 4 },
  'Gliscor': { forca: 2, inteligencia: 4, salto: 4 },
  'Gloom': { forca: 2, inteligencia: 3, salto: 2 },
  'Gogoat': { forca: 5, inteligencia: 4, salto: 4 },
  'Golbat': { forca: 3, inteligencia: 4, salto: 1 },
  'Goldeen': { forca: 1, inteligencia: 4, salto: 3 },
  'Golduck': { forca: 4, inteligencia: 5, salto: 3 },
  'Golem': { forca: 4, inteligencia: 3, salto: 2 },
  'Golem de Alola': { forca: 4, inteligencia: 3, salto: 2 },
  'Golett': { forca: 4, inteligencia: 2, salto: 1 },
  'Golisopod': { forca: 5, inteligencia: 4, salto: 3 },
  'Golurk': { forca: 6, inteligencia: 4, salto: 1 },
  'Goodra': { forca: 5, inteligencia: 5, salto: 4 },
  'Goomy': { forca: 2, inteligencia: 3, salto: 1 },
  'Gorebyss': { forca: 3, inteligencia: 4, salto: 2 },
  'Gothita': { forca: 1, inteligencia: 4, salto: 1 },
  'Gothitelle': { forca: 2, inteligencia: 5, salto: 1 },
  'Gothorita': { forca: 1, inteligencia: 4, salto: 1 },
  'Gourgeist': { forca: 4, inteligencia: 4, salto: 2 },
  'Grandbull': { forca: 3, inteligencia: 4, salto: 2 },
  'Graveler': { forca: 3, inteligencia: 2, salto: 2 },
  'Graveler de Alola': { forca: 3, inteligencia: 2, salto: 2 },
  'Greninja': { forca: 3, inteligencia: 5, salto: 5 },
  'Grimer': { forca: 2, inteligencia: 3, salto: 1 },
  'Grimer de Alola': { forca: 2, inteligencia: 3, salto: 1 },
  'Grotle': { forca: 2, inteligencia: 3, salto: 1 },
  'Groudon': { forca: 10, inteligencia: 7, salto: 5 },
  'Grovyle': { forca: 2, inteligencia: 3, salto: 5 },
  'Growlithe': { forca: 2, inteligencia: 4, salto: 2 },
  'Grubbin': { forca: 1, inteligencia: 2, salto: 1 },
  'Grumpig': { forca: 3, inteligencia: 4, salto: 6 },
  'Gulpin': { forca: 2, inteligencia: 3, salto: 1 },
  'Gumshoos': { forca: 3, inteligencia: 4, salto: 2 },
  'Gurdurr': { forca: 5, inteligencia: 3, salto: 4 },
  'Guzzlord': { forca: 10, inteligencia: 2, salto: 1 },
  'Gyarados': { forca: 6, inteligencia: 4, salto: 4 },
  'Hakamo-O': { forca: 3, inteligencia: 4, salto: 3 },
  'Happiny': { forca: 1, inteligencia: 3, salto: 2 },
  'Hariyama': { forca: 6, inteligencia: 4, salto: 1 },
  'Haunter': { forca: 2, inteligencia: 3, salto: '' },
  'Hawlucha': { forca: 4, inteligencia: 4, salto: 4 },
  'Haxorus': { forca: 5, inteligencia: 4, salto: 4 },
  'Heatmor': { forca: 3, inteligencia: 4, salto: 2 },
  'Heatran': { forca: 10, inteligencia: 5, salto: 1 },
  'Heliolisk': { forca: 3, inteligencia: 4, salto: 4 },
  'Helioptile': { forca: 2, inteligencia: 3, salto: 2 },
  'Heracross': { forca: 5, inteligencia: 4, salto: 4 },
  'Herdier': { forca: 3, inteligencia: 4, salto: 3 },
  'Hippopotas': { forca: 2, inteligencia: 4, salto: 2 },
  'Hippowdon': { forca: 4, inteligencia: 4, salto: 3 },
  'Hitmonchan': { forca: 4, inteligencia: 4, salto: 3 },
  'Hitmonlee': { forca: 3, inteligencia: 4, salto: 6 },
  'Hitmontop': { forca: 3, inteligencia: 4, salto: 2 },
  'Ho-oh': { forca: 6, inteligencia: 7, salto: 6 },
  'Honchkrow': { forca: 2, inteligencia: 4, salto: 3 },
  'Honedge': { forca: 2, inteligencia: 3, salto: 1 },
  'Hoopa': { forca: 10, inteligencia: 6, salto: 3 },
  'Hoothoot': { forca: 1, inteligencia: 3, salto: 3 },
  'Hoppip': { forca: 1, inteligencia: 3, salto: 5 },
  'Horsea': { forca: 1, inteligencia: 3, salto: 1 },
  'Houndoom': { forca: 1, inteligencia: 3, salto: 3 },
  'Houndour': { forca: 1, inteligencia: 3, salto: 3 },
  'Huntail': { forca: 3, inteligencia: 4, salto: 2 },
  'Hydreigon': { forca: 6, inteligencia: 4, salto: 4 },
  'Hypno': { forca: 3, inteligencia: 5, salto: 3 },
  'Igglybuff': { forca: 1, inteligencia: 3, salto: 3 },
  'Illumise': { forca: 1, inteligencia: 4, salto: 3 },
  'Incineroar': { forca: 7, inteligencia: 5, salto: 4 },
  'Infernape': { forca: 5, inteligencia: 4, salto: 4 },
  'Inkay': { forca: 2, inteligencia: 4, salto: 2 },
  'Ivyssauro': { forca: 2, inteligencia: 3, salto: 2 },
  'Jangmo-O': { forca: 2, inteligencia: 3, salto: 2 },
  'Jellicent': { forca: 3, inteligencia: 4, salto: 2 },
  'Jiggypuff': { forca: 1, inteligencia: 3, salto: 3 },
  'Jirachi': { forca: 3, inteligencia: 7, salto: 6 },
  'Jolteon': { forca: 2, inteligencia: 4, salto: 2 },
  'Joltik': { forca: 1, inteligencia: 3, salto: 3 },
  'Jumpluff': { forca: 1, inteligencia: 4, salto: 7 },
  'Jynx': { forca: 2, inteligencia: 5, salto: 3 },
  'Kabuto': { forca: 1, inteligencia: 2, salto: 1 },
  'Kabutops': { forca: 3, inteligencia: 4, salto: 3 },
  'Kadabra': { forca: 2, inteligencia: 5, salto: 2 },
  'Kakuna': { forca: 2, inteligencia: 2, salto: 4 },
  'Kangaskhan': { forca: 4, inteligencia: 4, salto: 5 },
  'Karrablast': { forca: 2, inteligencia: 4, salto: 3 },
  'Kartana': { forca: 7, inteligencia: 4, salto: 4 },
  'Kecleon': { forca: 2, inteligencia: 4, salto: 4 },
  'Keldeo': { forca: 5, inteligencia: 5, salto: 4 },
  'Kingdra': { forca: 5, inteligencia: 5, salto: 1 },
  'Kingler': { forca: 4, inteligencia: 4, salto: 1 },
  'Kirlia': { forca: 1, inteligencia: 5, salto: 2 },
  'Klang': { forca: 3, inteligencia: 4, salto: 1 },
  'Klekfi': { forca: 2, inteligencia: 4, salto: 2 },
  'Klink': { forca: 2, inteligencia: 4, salto: 1 },
  'Klinklang': { forca: 4, inteligencia: 5, salto: 1 },
  'Koffing': { forca: 1, inteligencia: 3, salto: 2 },
  'Komala': { forca: 2, inteligencia: 3, salto: 2 },
  'Kommo-O': { forca: 5, inteligencia: 4, salto: 4 },
  'Krabby': { forca: 1, inteligencia: 3, salto: 1 },
  'Kricketot': { forca: 1, inteligencia: 2, salto: 3 },
  'Kricketune': { forca: 2, inteligencia: 4, salto: 3 },
  'Krokorok': { forca: 3, inteligencia: 4, salto: 3 },
  'Krookodile': { forca: 4, inteligencia: 4, salto: 3 },
  'Kyogre': { forca: 10, inteligencia: 7, salto: 7 },
  'Kyurem': { forca: 7, inteligencia: 6, salto: 5 },
  'Lairon': { forca: 4, inteligencia: 4, salto: 3 },
  'Lampent': { forca: 1, inteligencia: 4, salto: 1 },
  'Landorus': { forca: 6, inteligencia: 5, salto: 4 },
  'Lanturn': { forca: 2, inteligencia: 4, salto: 3 },
  'Lapras': { forca: 6, inteligencia: 4, salto: 1 },
  'Larvesta': { forca: 1, inteligencia: 4, salto: 2 },
  'Larvitar': { forca: 2, inteligencia: 3, salto: 1 },
  'Latias': { forca: 4, inteligencia: 7, salto: 10 },
  'Latios': { forca: 4, inteligencia: 7, salto: 10 },
  'Leafeon': { forca: 2, inteligencia: 4, salto: 5 },
  'Leavanny': { forca: 3, inteligencia: 4, salto: 3 },
  'Ledian': { forca: 2, inteligencia: 4, salto: 2 },
  'Ledyba': { forca: 1, inteligencia: 2, salto: 2 },
  'Lickilicky': { forca: 4, inteligencia: 4, salto: 3 },
  'Lickitung': { forca: 3, inteligencia: 3, salto: 3 },
  'Lileep': { forca: 2, inteligencia: 3, salto: 1 },
  'Lilligant': { forca: 2, inteligencia: 4, salto: 2 },
  'Lillipup': { forca: 2, inteligencia: 4, salto: 3 },
  'Linoone': { forca: 3, inteligencia: 4, salto: 3 },
  'Linoone de Galar': { forca: 3, inteligencia: 4, salto: 3 },
  'Litleo': { forca: 2, inteligencia: 3, salto: 2 },
  'Litten': { forca: 1, inteligencia: 3, salto: 1 },
  'Litwick': { forca: 1, inteligencia: 4, salto: 1 },
  'Lombre': { forca: 2, inteligencia: 3, salto: 3 },
  'Lopunny': { forca: 2, inteligencia: 3, salto: 6 },
  'Lotad': { forca: 1, inteligencia: 3, salto: 1 },
  'Loudred': { forca: 3, inteligencia: 4, salto: 3 },
  'Lucario': { forca: 4, inteligencia: 4, salto: 4 },
  'Ludicolo': { forca: 4, inteligencia: 4, salto: 4 },
  'Lugia': { forca: 7, inteligencia: 7, salto: 5 },
  'Lumineon': { forca: 2, inteligencia: 4, salto: 4 },
  'Lunala': { forca: 10, inteligencia: 5, salto: 4 },
  'Lunatone': { forca: 3, inteligencia: 4, salto: 1 },
  'Lurantis': { forca: 3, inteligencia: 4, salto: 4 },
  'Luvdisc': { forca: 1, inteligencia: 3, salto: 2 },
  'Luxio': { forca: 2, inteligencia: 3, salto: 3 },
  'Luxray': { forca: 3, inteligencia: 4, salto: 4 },
  'Lycanroc': { forca: 2, inteligencia: 5, salto: 2 },
  'Lycanroc (Forma Crepuscular)': { forca: 2, inteligencia: 5, salto: 2 },
  'Lycanroc (Forma Noturna)': { forca: 2, inteligencia: 5, salto: 2 },
  'Machamp': { forca: 8, inteligencia: 4, salto: 4 },
  'Machoke': { forca: 6, inteligencia: 3, salto: 3 },
  'Machop': { forca: 3, inteligencia: 3, salto: 3 },
  'Magby': { forca: 1, inteligencia: 2, salto: 1 },
  'Magcargo': { forca: 3, inteligencia: 4, salto: 1 },
  'Magearna': { forca: 5, inteligencia: 4, salto: 3 },
  'Magikarp': { forca: 1, inteligencia: 2, salto: 4 },
  'Magmar': { forca: 4, inteligencia: 4, salto: 3 },
  'Magmortar': { forca: 5, inteligencia: 4, salto: 3 },
  'Magnemite': { forca: 1, inteligencia: 3, salto: '' },
  'Magneton': { forca: 3, inteligencia: 3, salto: '' },
  'Magnezone': { forca: 4, inteligencia: 4, salto: '' },
  'Makuhita': { forca: 3, inteligencia: 4, salto: 1 },
  'Malamar': { forca: 4, inteligencia: 5, salto: 2 },
  'Mamoswine': { forca: 6, inteligencia: 4, salto: 3 },
  'Manaphy': { forca: 2, inteligencia: 7, salto: 4 },
  'Mandibuzz': { forca: 3, inteligencia: 4, salto: 3 },
  'Manectric': { forca: 3, inteligencia: 4, salto: 3 },
  'Mankey': { forca: 2, inteligencia: 4, salto: 5 },
  'Mantine': { forca: 4, inteligencia: 4, salto: 4 },
  'Mantyke': { forca: 2, inteligencia: 2, salto: 4 },
  'Maractus': { forca: 2, inteligencia: 4, salto: 2 },
  'Mareanie': { forca: 2, inteligencia: 3, salto: 3 },
  'Mareep': { forca: 1, inteligencia: 3, salto: 2 },
  'Marill': { forca: 1, inteligencia: 3, salto: 2 },
  'Marowak': { forca: 4, inteligencia: 5, salto: 4 },
  'Marowak de Alola': { forca: 4, inteligencia: 5, salto: 4 },
  'Marshadow': { forca: 5, inteligencia: 4, salto: 3 },
  'Marshtomp': { forca: 2, inteligencia: 3, salto: 1 },
  'Masquerain': { forca: 1, inteligencia: 4, salto: 2 },
  'Mawile': { forca: 1, inteligencia: 4, salto: 3 },
  'Medicham': { forca: 4, inteligencia: 4, salto: 5 },
  'Meditite': { forca: 2, inteligencia: 4, salto: 4 },
  'Meganium': { forca: 2, inteligencia: 3, salto: 3 },
  'Meloetta': { forca: 4, inteligencia: 5, salto: 7 },
  'Meowth': { forca: 1, inteligencia: 4, salto: 4 },
  'Meowth de Alola': { forca: 1, inteligencia: 4, salto: 4 },
  'Meowth de Galar': { forca: 1, inteligencia: 4, salto: 4 },
  'Mesprit': { forca: 2, inteligencia: 7, salto: 5 },
  'Metagross': { forca: 8, inteligencia: 7, salto: 4 },
  'Metang': { forca: 4, inteligencia: 6, salto: 1 },
  'Metapod': { forca: 2, inteligencia: 2, salto: 4 },
  'Mew': { forca: 7, inteligencia: 4, salto: 4 },
  'Mewostic': { forca: 3, inteligencia: 5, salto: 4 },
  'Mewtwo': { forca: 10, inteligencia: 7, salto: 7 },
  'Mienfoo': { forca: 3, inteligencia: 4, salto: 3 },
  'Mienshao': { forca: 4, inteligencia: 4, salto: 4 },
  'Mightyena': { forca: 3, inteligencia: 4, salto: 3 },
  'Milotic': { forca: 4, inteligencia: 4, salto: 4 },
  'Miltank': { forca: 3, inteligencia: 4, salto: 3 },
  'Mime Jr.': { forca: 1, inteligencia: 4, salto: 2 },
  'Mimikyu': { forca: 2, inteligencia: 4, salto: 3 },
  'Minccino': { forca: 1, inteligencia: 4, salto: 2 },
  'Minior': { forca: 3, inteligencia: 3, salto: 2 },
  'Minun': { forca: 1, inteligencia: 4, salto: 2 },
  'Misdreavus': { forca: 1, inteligencia: 4, salto: '' },
  'Mismagius': { forca: 2, inteligencia: 4, salto: '' },
  'Moltres': { forca: 5, inteligencia: 7, salto: 5 },
  'Monferno': { forca: 3, inteligencia: 4, salto: 3 },
  'Morelull': { forca: 1, inteligencia: 3, salto: 2 },
  'Mothim': { forca: 2, inteligencia: 4, salto: 2 },
  'Mr. Mime': { forca: 2, inteligencia: 5, salto: 3 },
  'Mr. Mime de Galar': { forca: 2, inteligencia: 5, salto: 3 },
  'Mudbray': { forca: 3, inteligencia: 3, salto: 3 },
  'Mudkip': { forca: 1, inteligencia: 3, salto: 1 },
  'Mudsdale': { forca: 6, inteligencia: 4, salto: 4 },
  'Muk': { forca: 4, inteligencia: 4, salto: 1 },
  'Muk de Alola': { forca: 4, inteligencia: 4, salto: 1 },
  'Munchlax': { forca: 3, inteligencia: 3, salto: 3 },
  'Munna': { forca: 2, inteligencia: 5, salto: 1 },
  'Murkrow': { forca: 1, inteligencia: 4, salto: 2 },
  'Musharna': { forca: 3, inteligencia: 6, salto: 3 },
  'Naganadel': { forca: 5, inteligencia: 5, salto: 3 },
  'Natu': { forca: 1, inteligencia: 4, salto: 3 },
  'Necrozma': { forca: 10, inteligencia: 5, salto: 7 },
  'Necrozma Asas do Alvorecer': { forca: 10, inteligencia: 5, salto: 7 },
  'Necrozma Juba do Crepúsculo': { forca: 10, inteligencia: 5, salto: 7 },
  'Necrozma Ultra': { forca: 10, inteligencia: 5, salto: 7 },
  'Nidoking': { forca: 4, inteligencia: 4, salto: 2 },
  'Nidoqueen': { forca: 4, inteligencia: 4, salto: 2 },
  'Nidoran F': { forca: 1, inteligencia: 3, salto: 2 },
  'Nidoran M': { forca: 1, inteligencia: 3, salto: 2 },
  'Nidorina': { forca: 2, inteligencia: 3, salto: 3 },
  'Nidorino': { forca: 2, inteligencia: 3, salto: 3 },
  'Nihilego': { forca: 7, inteligencia: 4, salto: 3 },
  'Nincada': { forca: 1, inteligencia: 3, salto: 3 },
  'Ninetales Ninetales Ninetales': { forca: 3, inteligencia: 4, salto: 4 },
  'Ninjask': { forca: 2, inteligencia: 4, salto: 2 },
  'Noctowl': { forca: 3, inteligencia: 4, salto: 3 },
  'Noibat': { forca: 2, inteligencia: 3, salto: 1 },
  'Noivern': { forca: 4, inteligencia: 4, salto: 4 },
  'Nosepass': { forca: 3, inteligencia: 4, salto: 1 },
  'Numel': { forca: 2, inteligencia: 3, salto: 2 },
  'Nuzleaf': { forca: 3, inteligencia: 4, salto: 4 },
  'Octillery': { forca: 2, inteligencia: 4, salto: 3 },
  'Oddish': { forca: 1, inteligencia: 2, salto: 1 },
  'Omanyte': { forca: 1, inteligencia: 3, salto: 1 },
  'Omastar': { forca: 2, inteligencia: 4, salto: 2 },
  'Onix': { forca: 5, inteligencia: 4, salto: 3 },
  'Oranguru': { forca: 3, inteligencia: 5, salto: 4 },
  'Oricorio': { forca: 1, inteligencia: 3, salto: 4 },
  "Oricorio (Estilo Pa'u)": { forca: 1, inteligencia: 3, salto: 4 },
  'Oricorio (Estilo Pom-Pom)': { forca: 1, inteligencia: 3, salto: 4 },
  'Oricorio (Estilo Sensu)': { forca: 1, inteligencia: 3, salto: 4 },
  'Oshawott': { forca: 2, inteligencia: 3, salto: 2 },
  'Pachirisu': { forca: 1, inteligencia: 4, salto: 3 },
  'Palkia': { forca: 10, inteligencia: 7, salto: 8 },
  'Palossand': { forca: 5, inteligencia: 4, salto: 1 },
  'Palpitoad': { forca: 3, inteligencia: 4, salto: 4 },
  'Pancham': { forca: 2, inteligencia: 3, salto: 3 },
  'Pangoro': { forca: 5, inteligencia: 4, salto: 4 },
  'Panpour': { forca: 2, inteligencia: 4, salto: 4 },
  'Pansage': { forca: 2, inteligencia: 4, salto: 4 },
  'Pansear': { forca: 2, inteligencia: 4, salto: 4 },
  'Paras': { forca: 1, inteligencia: 3, salto: 1 },
  'Parasect': { forca: 3, inteligencia: 4, salto: 2 },
  'Passimian': { forca: 4, inteligencia: 4, salto: 4 },
  'Patrat': { forca: 2, inteligencia: 3, salto: 3 },
  'Pawniard': { forca: 3, inteligencia: 3, salto: 3 },
  'Pelipper': { forca: 3, inteligencia: 4, salto: 2 },
  'Persian': { forca: 3, inteligencia: 4, salto: 5 },
  'Persian de Alola': { forca: 3, inteligencia: 4, salto: 5 },
  'Petilil': { forca: 1, inteligencia: 4, salto: 2 },
  'Phanpy': { forca: 2, inteligencia: 3, salto: 3 },
  'Phantump': { forca: 2, inteligencia: 3, salto: 1 },
  'Pheromosa': { forca: 5, inteligencia: 4, salto: 8 },
  'Phione': { forca: 1, inteligencia: 4, salto: 4 },
  'Pichu': { forca: 1, inteligencia: 3, salto: 2 },
  'Pidgeot': { forca: 4, inteligencia: 4, salto: 3 },
  'Pidgeotto': { forca: 2, inteligencia: 3, salto: 3 },
  'Pidgey': { forca: 1, inteligencia: 3, salto: 3 },
  'Pidove': { forca: 2, inteligencia: 3, salto: 3 },
  'Pignite': { forca: 5, inteligencia: 4, salto: 4 },
  'Pikachu': { forca: 1, inteligencia: 4, salto: 3 },
  'Pikipek': { forca: 2, inteligencia: 3, salto: 3 },
  'Piloswine': { forca: 4, inteligencia: 3, salto: 2 },
  'Pineco': { forca: 1, inteligencia: 3, salto: 4 },
  'Pinsir': { forca: 5, inteligencia: 4, salto: 3 },
  'Piplup': { forca: 1, inteligencia: 2, salto: 1 },
  'Plusle': { forca: 1, inteligencia: 4, salto: 2 },
  'Poipole': { forca: 2, inteligencia: 3, salto: 3 },
  'Politoed': { forca: 3, inteligencia: 4, salto: 6 },
  'Poliwag': { forca: 1, inteligencia: 3, salto: 2 },
  'Poliwhirl': { forca: 3, inteligencia: 4, salto: 4 },
  'Poliwrath': { forca: 5, inteligencia: 4, salto: 5 },
  'Ponyta': { forca: 2, inteligencia: 4, salto: 4 },
  'Ponyta de Galar': { forca: 2, inteligencia: 4, salto: 4 },
  'Poochyena': { forca: 1, inteligencia: 3, salto: 2 },
  'Popplio': { forca: 1, inteligencia: 3, salto: 2 },
  'Porygon': { forca: 1, inteligencia: 4, salto: 2 },
  'Porygon 2': { forca: 1, inteligencia: 5, salto: 3 },
  'Porygon Z': { forca: 1, inteligencia: 6, salto: 3 },
  'Primeape': { forca: 4, inteligencia: 4, salto: 5 },
  'Prinplup': { forca: 2, inteligencia: 3, salto: 2 },
  'Probopass': { forca: 5, inteligencia: 4, salto: 1 },
  'Psyduck': { forca: 1, inteligencia: 4, salto: 2 },
  'Pumpkaboo': { forca: 2, inteligencia: 3, salto: 2 },
  'Pupitar': { forca: 3, inteligencia: 4, salto: 5 },
  'Purugly': { forca: 2, inteligencia: 4, salto: 3 },
  'Pyroar': { forca: 4, inteligencia: 5, salto: 3 },
  'Pyukumuku': { forca: 1, inteligencia: 3, salto: 1 },
  'Quagsire': { forca: 3, inteligencia: 4, salto: 3 },
  'Quilava': { forca: 2, inteligencia: 3, salto: 3 },
  'Quilladin': { forca: 2, inteligencia: 4, salto: 2 },
  'Qwilfish': { forca: 1, inteligencia: 3, salto: 3 },
  'Raichu Raichu Raichu': { forca: 2, inteligencia: 4, salto: 3 },
  'Raikou': { forca: 5, inteligencia: 7, salto: 7 },
  'Ralts': { forca: 1, inteligencia: 4, salto: 2 },
  'Rampardos': { forca: 4, inteligencia: 4, salto: 4 },
  'Rapidash': { forca: 2, inteligencia: 4, salto: 4 },
  'Rapidash de Galar': { forca: 2, inteligencia: 4, salto: 4 },
  'Raticate': { forca: 3, inteligencia: 4, salto: 3 },
  'Raticate de Alola': { forca: 3, inteligencia: 4, salto: 3 },
  'Rattata': { forca: 1, inteligencia: 3, salto: 2 },
  'Rattata de Alola': { forca: 1, inteligencia: 3, salto: 2 },
  'Rayquaza': { forca: 10, inteligencia: 7, salto: 10 },
  'Regice': { forca: 9, inteligencia: 5, salto: 1 },
  'Regigigas': { forca: 10, inteligencia: 7, salto: 1 },
  'Regirock': { forca: 9, inteligencia: 5, salto: 1 },
  'Registeel': { forca: 9, inteligencia: 5, salto: 1 },
  'Relicanth': { forca: 1, inteligencia: 3, salto: 1 },
  'Remoraid': { forca: 1, inteligencia: 4, salto: 3 },
  'Reshiram': { forca: 6, inteligencia: 5, salto: 4 },
  'Reuniclus': { forca: 2, inteligencia: 6, salto: 3 },
  'Rhydon': { forca: 4, inteligencia: 4, salto: 2 },
  'Rhyhorn': { forca: 4, inteligencia: 3, salto: 2 },
  'Rhyperior': { forca: 5, inteligencia: 4, salto: 1 },
  'Ribombee': { forca: 1, inteligencia: 3, salto: 2 },
  'Riolu': { forca: 2, inteligencia: 3, salto: 3 },
  'Rockruff': { forca: 2, inteligencia: 3, salto: 2 },
  'Roggenrola': { forca: 3, inteligencia: 4, salto: 1 },
  'Roselia': { forca: 2, inteligencia: 4, salto: 3 },
  'Roserade': { forca: 2, inteligencia: 4, salto: 3 },
  'Rotom': { forca: 1, inteligencia: 4, salto: 4 },
  'Rotom Calor': { forca: 1, inteligencia: 4, salto: 4 },
  'Rotom Cortar': { forca: 1, inteligencia: 4, salto: 4 },
  'Rotom Gelar': { forca: 1, inteligencia: 4, salto: 4 },
  'Rotom Girar': { forca: 1, inteligencia: 4, salto: 4 },
  'Rotom Lavar': { forca: 1, inteligencia: 4, salto: 4 },
  'Rowlet': { forca: 1, inteligencia: 3, salto: 2 },
  'Rufflet': { forca: 2, inteligencia: 3, salto: 3 },
  'Sableye': { forca: 1, inteligencia: 4, salto: 4 },
  'Salamence': { forca: 5, inteligencia: 4, salto: 4 },
  'Salandit': { forca: 1, inteligencia: 3, salto: 2 },
  'Salazzle': { forca: 3, inteligencia: 4, salto: 4 },
  'Samurott': { forca: 4, inteligencia: 4, salto: 3 },
  'Sandile': { forca: 3, inteligencia: 4, salto: 2 },
  'Sandshrew': { forca: 1, inteligencia: 3, salto: 2 },
  'Sandshrew de Alola': { forca: 1, inteligencia: 3, salto: 2 },
  'Sandygast': { forca: 3, inteligencia: 3, salto: 1 },
  'Sawk': { forca: 5, inteligencia: 4, salto: 4 },
  'Sawsbuck': { forca: 4, inteligencia: 4, salto: 4 },
  'Scatterbug': { forca: 1, inteligencia: 3, salto: 1 },
  'Sceptile': { forca: 4, inteligencia: 4, salto: 6 },
  'Scizor': { forca: 4, inteligencia: 4, salto: 5 },
  'Scolipede': { forca: 4, inteligencia: 4, salto: 3 },
  'Scrafty': { forca: 3, inteligencia: 5, salto: 4 },
  'Scraggy': { forca: 3, inteligencia: 4, salto: 3 },
  'Scyther': { forca: 3, inteligencia: 4, salto: 5 },
  'Seadra': { forca: 3, inteligencia: 4, salto: 1 },
  'Seaking': { forca: 3, inteligencia: 4, salto: 3 },
  'Sealeo': { forca: 3, inteligencia: 4, salto: 3 },
  'Seedot': { forca: 1, inteligencia: 3, salto: 4 },
  'Seel': { forca: 3, inteligencia: 4, salto: 2 },
  'Seismitoad': { forca: 4, inteligencia: 4, salto: 6 },
  'Sentret': { forca: 1, inteligencia: 3, salto: 3 },
  'Serperior': { forca: 4, inteligencia: 5, salto: 2 },
  'Servine': { forca: 3, inteligencia: 4, salto: 1 },
  'Seviper': { forca: 3, inteligencia: 4, salto: 4 },
  'Sewaddle': { forca: 1, inteligencia: 2, salto: 2 },
  'Sharpedo': { forca: 4, inteligencia: 4, salto: 5 },
  'Shaymin': { forca: 2, inteligencia: 7, salto: 5 },
  'Shedinja': { forca: 1, inteligencia: 4, salto: 2 },
  'Shelgon': { forca: 4, inteligencia: 3, salto: 2 },
  'Shellder': { forca: 1, inteligencia: 3, salto: 2 },
  'Shellos': { forca: 1, inteligencia: 3, salto: 1 },
  'Shelmet': { forca: 1, inteligencia: 3, salto: 1 },
  'Shieldon': { forca: 3, inteligencia: 3, salto: 3 },
  'Shiftry': { forca: 4, inteligencia: 4, salto: 4 },
  'Shiinotic': { forca: 1, inteligencia: 3, salto: 2 },
  'Shinx': { forca: 1, inteligencia: 3, salto: 2 },
  'Shroomish': { forca: 1, inteligencia: 3, salto: 2 },
  'Shuckle': { forca: 2, inteligencia: 3, salto: 1 },
  'Shuppet': { forca: 1, inteligencia: 4, salto: 3 },
  'Sigilyph': { forca: 2, inteligencia: 6, salto: 3 },
  'Silcoon': { forca: 2, inteligencia: 2, salto: 4 },
  'Silvally': { forca: 6, inteligencia: 5, salto: 6 },
  'Silvally (Memória Chama)': { forca: 6, inteligencia: 5, salto: 6 },
  'Silvally (Memória Dragão)': { forca: 6, inteligencia: 5, salto: 6 },
  'Silvally (Memória Eletro)': { forca: 6, inteligencia: 5, salto: 6 },
  'Silvally (Memória Fada)': { forca: 6, inteligencia: 5, salto: 6 },
  'Silvally (Memória Fantasma)': { forca: 6, inteligencia: 5, salto: 6 },
  'Silvally (Memória Gelo)': { forca: 6, inteligencia: 5, salto: 6 },
  'Silvally (Memória Grama)': { forca: 6, inteligencia: 5, salto: 6 },
  'Silvally (Memória Inseto)': { forca: 6, inteligencia: 5, salto: 6 },
  'Silvally (Memória Luta)': { forca: 6, inteligencia: 5, salto: 6 },
  'Silvally (Memória Metálico)': { forca: 6, inteligencia: 5, salto: 6 },
  'Silvally (Memória Pedra)': { forca: 6, inteligencia: 5, salto: 6 },
  'Silvally (Memória Psíquico)': { forca: 6, inteligencia: 5, salto: 6 },
  'Silvally (Memória Sombrio)': { forca: 6, inteligencia: 5, salto: 6 },
  'Silvally (Memória Terra)': { forca: 6, inteligencia: 5, salto: 6 },
  'Silvally (Memória Veneno)': { forca: 6, inteligencia: 5, salto: 6 },
  'Silvally (Memória Voador)': { forca: 6, inteligencia: 5, salto: 6 },
  'Silvally (Memória Água)': { forca: 6, inteligencia: 5, salto: 6 },
  'Simipour': { forca: 3, inteligencia: 4, salto: 5 },
  'Simisage': { forca: 3, inteligencia: 4, salto: 5 },
  'Simisear': { forca: 3, inteligencia: 4, salto: 5 },
  'Skarmory': { forca: 4, inteligencia: 4, salto: 3 },
  'Skiddo': { forca: 4, inteligencia: 3, salto: 3 },
  'Skiploom': { forca: 1, inteligencia: 4, salto: 6 },
  'Skitty': { forca: 1, inteligencia: 4, salto: 2 },
  'Skorupi': { forca: 1, inteligencia: 3, salto: 2 },
  'Skrelp': { forca: 1, inteligencia: 3, salto: 1 },
  'Skuntank': { forca: 2, inteligencia: 4, salto: 3 },
  'Slaking': { forca: 9, inteligencia: 4, salto: 4 },
  'Slakoth': { forca: 2, inteligencia: 1, salto: 2 },
  'Sliggoo': { forca: 2, inteligencia: 4, salto: 1 },
  'Slowbro': { forca: 4, inteligencia: 5, salto: 1 },
  'Slowking': { forca: 4, inteligencia: 7, salto: 1 },
  'Slowpoke': { forca: 2, inteligencia: 4, salto: 1 },
  'Slugma': { forca: 2, inteligencia: 3, salto: 1 },
  'Slurpuff': { forca: 1, inteligencia: 4, salto: 4 },
  'Smeargle': { forca: 3, inteligencia: 4, salto: 3 },
  'Smoochum': { forca: 1, inteligencia: 4, salto: 2 },
  'Sneasel': { forca: 3, inteligencia: 4, salto: 3 },
  'Snivy': { forca: 2, inteligencia: 4, salto: 1 },
  'Snorlax': { forca: 7, inteligencia: 4, salto: 1 },
  'Snorunt': { forca: 1, inteligencia: 3, salto: 2 },
  'Snover': { forca: 3, inteligencia: 4, salto: 3 },
  'Snubbull': { forca: 1, inteligencia: 4, salto: 2 },
  'Solgaleo': { forca: 10, inteligencia: 5, salto: 5 },
  'Solosis': { forca: 1, inteligencia: 4, salto: 1 },
  'Solrock': { forca: 3, inteligencia: 4, salto: 1 },
  'Spearow': { forca: 1, inteligencia: 3, salto: 3 },
  'Spheal': { forca: 1, inteligencia: 3, salto: 3 },
  'Spinarak': { forca: 1, inteligencia: 2, salto: 4 },
  'Spinda': { forca: 1, inteligencia: 3, salto: 3 },
  'Spiritomb': { forca: 1, inteligencia: 5, salto: 2 },
  'Spoink': { forca: 1, inteligencia: 4, salto: 5 },
  'Spritzee': { forca: 1, inteligencia: 3, salto: 2 },
  'Squirtle': { forca: 1, inteligencia: 3, salto: 2 },
  'Stakataka': { forca: 8, inteligencia: 4, salto: 3 },
  'Stantler': { forca: 3, inteligencia: 4, salto: 4 },
  'Staraptor': { forca: 3, inteligencia: 4, salto: 3 },
  'Staravia': { forca: 2, inteligencia: 4, salto: 3 },
  'Starly': { forca: 1, inteligencia: 3, salto: 3 },
  'Starmie': { forca: 3, inteligencia: 4, salto: 2 },
  'Staryu': { forca: 2, inteligencia: 4, salto: 2 },
  'Steelix': { forca: 5, inteligencia: 4, salto: 3 },
  'Steenee': { forca: 3, inteligencia: 4, salto: 3 },
  'Stoutland': { forca: 4, inteligencia: 4, salto: 3 },
  'Stufful': { forca: 4, inteligencia: 3, salto: 3 },
  'Stunfisk': { forca: 1, inteligencia: 2, salto: 2 },
  'Stunfisk de Galar': { forca: 1, inteligencia: 2, salto: 2 },
  'Stunky': { forca: 1, inteligencia: 3, salto: 3 },
  'Sudowoodo': { forca: 4, inteligencia: 4, salto: 2 },
  'Suicune': { forca: 5, inteligencia: 7, salto: 7 },
  'Sunflora': { forca: 1, inteligencia: 4, salto: 2 },
  'Sunkern': { forca: 1, inteligencia: 3, salto: 1 },
  'Surskit': { forca: 1, inteligencia: 3, salto: 2 },
  'Swablu': { forca: 1, inteligencia: 3, salto: 2 },
  'Swadloon': { forca: 2, inteligencia: 3, salto: 2 },
  'Swalot': { forca: 4, inteligencia: 4, salto: 1 },
  'Swampert': { forca: 4, inteligencia: 4, salto: 2 },
  'Swanna': { forca: 2, inteligencia: 4, salto: 3 },
  'Swellow': { forca: 4, inteligencia: 4, salto: 3 },
  'Swinub': { forca: 2, inteligencia: 2, salto: 2 },
  'Swirlix': { forca: 1, inteligencia: 3, salto: 1 },
  'Swoobat': { forca: 2, inteligencia: 5, salto: 2 },
  'Sylveon': { forca: 2, inteligencia: 4, salto: 3 },
  'Taillow': { forca: 1, inteligencia: 3, salto: 3 },
  'Talonflame': { forca: 3, inteligencia: 4, salto: 2 },
  'Tangela': { forca: 2, inteligencia: 4, salto: 2 },
  'Tangrowth': { forca: 4, inteligencia: 4, salto: 2 },
  'Tapu Bulu': { forca: 10, inteligencia: 5, salto: 5 },
  'Tapu Fini': { forca: 10, inteligencia: 5, salto: 5 },
  'Tapu Koko': { forca: 10, inteligencia: 5, salto: 5 },
  'Tapu Lele': { forca: 10, inteligencia: 5, salto: 5 },
  'Tauros': { forca: 4, inteligencia: 4, salto: 2 },
  'Teddiursa': { forca: 1, inteligencia: 3, salto: 2 },
  'Tentacool': { forca: 2, inteligencia: 3, salto: 2 },
  'Tentacruel': { forca: 4, inteligencia: 4, salto: 3 },
  'Tepig': { forca: 3, inteligencia: 3, salto: 2 },
  'Terrakion': { forca: 5, inteligencia: 5, salto: 4 },
  'Throh': { forca: 5, inteligencia: 4, salto: 4 },
  'Thundurus': { forca: 5, inteligencia: 5, salto: 6 },
  'Timburr': { forca: 4, inteligencia: 2, salto: 4 },
  'Tipo Nulo': { forca: 4, inteligencia: 4, salto: 4 },
  'Tirtouga': { forca: 2, inteligencia: 4, salto: 2 },
  'Togedemaru': { forca: 1, inteligencia: 4, salto: 3 },
  'Togekiss': { forca: 3, inteligencia: 4, salto: 5 },
  'Togepi': { forca: 1, inteligencia: 2, salto: 1 },
  'Togetic': { forca: 2, inteligencia: 4, salto: 4 },
  'Torchic': { forca: 1, inteligencia: 2, salto: 1 },
  'Torkoal': { forca: 4, inteligencia: 4, salto: 2 },
  'Tornadus': { forca: 5, inteligencia: 5, salto: 6 },
  'Torracat': { forca: 3, inteligencia: 4, salto: 3 },
  'Torterra': { forca: 4, inteligencia: 4, salto: 1 },
  'Totodile': { forca: 1, inteligencia: 2, salto: 3 },
  'Toucannon': { forca: 4, inteligencia: 4, salto: 4 },
  'Toxapex': { forca: 4, inteligencia: 4, salto: 4 },
  'Toxicroak': { forca: 3, inteligencia: 4, salto: 5 },
  'Tranquill': { forca: 3, inteligencia: 4, salto: 4 },
  'Trapinch': { forca: 1, inteligencia: 3, salto: 1 },
  'Treecko': { forca: 1, inteligencia: 3, salto: 4 },
  'Trevenant': { forca: 3, inteligencia: 4, salto: 2 },
  'Tropius': { forca: 5, inteligencia: 4, salto: 4 },
  'Trubbish': { forca: 2, inteligencia: 4, salto: 1 },
  'Trumbeak': { forca: 3, inteligencia: 4, salto: 3 },
  'Tsareena': { forca: 4, inteligencia: 4, salto: 5 },
  'Turtonator': { forca: 4, inteligencia: 4, salto: 2 },
  'Turtwig': { forca: 1, inteligencia: 3, salto: 3 },
  'Tympole': { forca: 1, inteligencia: 4, salto: 3 },
  'Tynamo': { forca: 1, inteligencia: 4, salto: 2 },
  'Typhlosion': { forca: 4, inteligencia: 4, salto: 3 },
  'Tyranitar': { forca: 5, inteligencia: 4, salto: 3 },
  'Tyrantrum': { forca: 5, inteligencia: 4, salto: 2 },
  'Tyrogue': { forca: 2, inteligencia: 3, salto: 3 },
  'Tyrunt': { forca: 2, inteligencia: 4, salto: 2 },
  'Umbreon': { forca: 2, inteligencia: 4, salto: 4 },
  'Unfezant': { forca: 4, inteligencia: 4, salto: 4 },
  'Unown': { forca: 1, inteligencia: 5, salto: '' },
  'Ursaring': { forca: 4, inteligencia: 4, salto: 2 },
  'Uxie': { forca: 2, inteligencia: 7, salto: 5 },
  'Vanillish': { forca: 2, inteligencia: 4, salto: 2 },
  'Vanillite': { forca: 1, inteligencia: 4, salto: 2 },
  'Vanilluxe': { forca: 3, inteligencia: 4, salto: 2 },
  'Vaporeon': { forca: 2, inteligencia: 4, salto: 2 },
  'Venipede': { forca: 2, inteligencia: 2, salto: 3 },
  'Venomoth': { forca: 2, inteligencia: 4, salto: 2 },
  'Venonat': { forca: 1, inteligencia: 4, salto: 3 },
  'Venussauro': { forca: 4, inteligencia: 4, salto: 1 },
  'Vespiquen': { forca: 3, inteligencia: 4, salto: 4 },
  'Vibrava': { forca: 1, inteligencia: 4, salto: 3 },
  'Victini': { forca: 5, inteligencia: 4, salto: 7 },
  'Victreebel': { forca: 3, inteligencia: 4, salto: 3 },
  'Vigoroth': { forca: 3, inteligencia: 3, salto: 4 },
  'Vikavolt': { forca: 3, inteligencia: 4, salto: 1 },
  'Vileplume': { forca: 3, inteligencia: 4, salto: 3 },
  'Virizion': { forca: 5, inteligencia: 5, salto: 4 },
  'Vivillon': { forca: 2, inteligencia: 4, salto: 3 },
  'Volbeat': { forca: 1, inteligencia: 4, salto: 3 },
  'Volcanion': { forca: 8, inteligencia: 7, salto: 3 },
  'Volcarona': { forca: 3, inteligencia: 4, salto: 3 },
  'Voltorb': { forca: 1, inteligencia: 4, salto: 1 },
  'Vullaby': { forca: 1, inteligencia: 4, salto: 3 },
  'Vulpix': { forca: 1, inteligencia: 3, salto: 3 },
  'Vulpix de Alola': { forca: 1, inteligencia: 3, salto: 3 },
  'Wailmer': { forca: 4, inteligencia: 3, salto: 3 },
  'Wailord': { forca: 6, inteligencia: 4, salto: 3 },
  'Walrein': { forca: 4, inteligencia: 4, salto: 2 },
  'Wartortle': { forca: 2, inteligencia: 3, salto: 2 },
  'Watchog': { forca: 3, inteligencia: 4, salto: 4 },
  'Weavile': { forca: 4, inteligencia: 4, salto: 4 },
  'Weedle': { forca: 1, inteligencia: 2, salto: 2 },
  'Weepinbell': { forca: 2, inteligencia: 4, salto: 3 },
  'Weezing': { forca: 2, inteligencia: 4, salto: 4 },
  'Weezing de Galar': { forca: 2, inteligencia: 4, salto: 4 },
  'Whimsicott': { forca: 2, inteligencia: 5, salto: 6 },
  'Whirlipede': { forca: 3, inteligencia: 3, salto: 3 },
  'Whiscash': { forca: 2, inteligencia: 4, salto: 3 },
  'Whismur': { forca: 1, inteligencia: 3, salto: 2 },
  'Wiggytuff': { forca: 2, inteligencia: 4, salto: 5 },
  'Wimpod': { forca: 1, inteligencia: 2, salto: 1 },
  'Wingull': { forca: 1, inteligencia: 3, salto: 2 },
  'Wishiwashi': { forca: 1, inteligencia: 4, salto: 2 },
  'Wishiwashi (Forma Cardume)': { forca: 1, inteligencia: 4, salto: 2 },
  'Wobbuffet': { forca: 2, inteligencia: 5, salto: 2 },
  'Woobat': { forca: 1, inteligencia: 4, salto: 1 },
  'Wooper': { forca: 1, inteligencia: 3, salto: 3 },
  'Wormadam': { forca: 1, inteligencia: 4, salto: 3 },
  'Wormadam (Manto Arenoso)': { forca: 1, inteligencia: 4, salto: 3 },
  'Wormadam (Manto de Lixo)': { forca: 1, inteligencia: 4, salto: 3 },
  'Wurmple': { forca: 1, inteligencia: 2, salto: 2 },
  'Wynaut': { forca: 1, inteligencia: 3, salto: 4 },
  'Xatu': { forca: 2, inteligencia: 4, salto: 4 },
  'Xerneas': { forca: 8, inteligencia: 6, salto: 6 },
  'Xurkitree': { forca: 7, inteligencia: 4, salto: 5 },
  'Yamask': { forca: 2, inteligencia: 4, salto: 3 },
  'Yamask de Galar': { forca: 2, inteligencia: 4, salto: 3 },
  'Yanma': { forca: 2, inteligencia: 4, salto: 2 },
  'Yanmega': { forca: 3, inteligencia: 4, salto: 2 },
  'Yungoos': { forca: 2, inteligencia: 3, salto: 2 },
  'Yveltal': { forca: 5, inteligencia: 6, salto: 3 },
  'Zangoose': { forca: 3, inteligencia: 4, salto: 4 },
  'Zapdos': { forca: 5, inteligencia: 7, salto: 5 },
  'Zebstrika': { forca: 4, inteligencia: 4, salto: 5 },
  'Zekrom': { forca: 6, inteligencia: 5, salto: 4 },
  'Zeraora': { forca: 7, inteligencia: 6, salto: 5 },
  'Zigzagoon': { forca: 1, inteligencia: 3, salto: 3 },
  'Zigzagoon de Galar': { forca: 1, inteligencia: 3, salto: 3 },
  'Zoroark': { forca: 3, inteligencia: 4, salto: 3 },
  'Zorua': { forca: 2, inteligencia: 4, salto: 2 },
  'Zubat': { forca: 1, inteligencia: 3, salto: '' },
  'Zweilous': { forca: 3, inteligencia: 3, salto: 3 },
  'Zygarde': { forca: 8, inteligencia: 6, salto: 4 },
}
